const types = {
  REMOVE_CARD: '@TASKS/REMOVE_CARD',
  ADD_CARD: '@TASKS/ADD_CARD',
  UPDATE_CARD: '@TASKS/UPDATE_CARD',
  SET_CARD: '@TASKS/SET_CARD',
  ADD_COLUMN: '@TASKS/ADD_COLUMN',
  UPDATE_COLUMN_NAME: '@TASKS/UPDATE_COLUMN_NAME',
  SET_MODAL: '@TASKS/SET_MODAL'
}

export default types